### ISSUE TITLE
Error during compile

### ISSUE THREAD

**Issue by anasurimbo** [ONLYOFFICE/build_tools#127]
Hello.
ubuntu 14.04 
receiving error on compile action

```
Running "closure-compiler:js" (closure-compiler) task
Warning: Compilation error Use --force to continue.

Aborted due to warnings.
Error (grunt): 6
Error (./make.py): 1
```

My first run processed 2 days with 100% one core load
`step - Running "closure-compiler:js" (closure-compiler) task`

I enterupted process and launched it on more productive enviroment
As a result - 

```
Running "closure-compiler:js" (closure-compiler) task
Warning: Compilation error Use --force to continue.

Aborted due to warnings.
Error (grunt): 6
Error (./make.py): 1
```

**Comment by ShockwaveNN** [comment]
Hi, which java are you using?

**Comment by anasurimbo** [comment]
```
 java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1~14.04-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

**Comment by ShockwaveNN** [comment]
Java Version seems fine

Could you enter to `sdkjs` subdir and run
```
sudo npm install -g grunt-cli
npm install --prefix build
grunt --level=WHITESPACE_ONLY --base build --gruntfile build/Gruntfile.js
```

And see if this error happened again

Also this PC specs are you using?

**Comment by anasurimbo** [comment]
```
sudo npm install -g grunt-cli
npm install --prefix build
grunt --level=WHITESPACE_ONLY --base build --gruntfile build/Gruntfile.js
```
Complited without errors.

> Also this PC specs are you using?
I have aws-ec2 instance (t3a.2xlarge)
8 vCPUs 32 RAM

I have launched another clean compile process. 
It is still running (about 4 hours) and shows
`Running "closure-compiler:js" (closure-compiler) task`

**Comment by ShockwaveNN** [comment]
> It is still running (about 4 hours) and shows

This is not right, on my 8cpu and 16 RAM it takes around several minutes

So WHITEPSACE_ONLY is simple closure-compiler optimization

Now try to run full optimization

```
grunt --base build --gruntfile build/Gruntfile.js
```

It take around 2.5 minutes on my pc

```
time grunt --base build --gruntfile build/Gruntfile.js
...
real    2m22,091s
user    4m40,032s
sys     0m2,425s

```

**Comment by anasurimbo** [comment]
Hello.

Moved from AWS to ESXI VM. Clean ubuntu 14.04.06 install.
But now error showed something different

```
 phantomjs-prebuilt@2.1.16 install /root/oo/web-apps/build/node_modules/phantomjs-prebuilt
 node install.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/root/oo/web-apps/build/node_modules/phantomjs-prebuilt/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-25T15_43_46_572Z-debug.log
Error (npm): 1
Error (./make.py): 1

output of /root/.npm/_logs/2020-08-25T15_43_46_572Z-debug.log
```

```
21593 verbose lifecycle phantomjs-prebuilt@2.1.16~install: unsafe-perm in lifecycle false
21594 verbose lifecycle phantomjs-prebuilt@2.1.16~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/oo/web-apps/build/node_modules/phantomjs-prebuilt/node_modules/.bin
21595 verbose lifecycle phantomjs-prebuilt@2.1.16~install: CWD: /root/oo/web-apps/build/node_modules/phantomjs-prebuilt
21596 silly lifecycle phantomjs-prebuilt@2.1.16~install: Args: [ '-c', 'node install.js' ]
21597 silly lifecycle phantomjs-prebuilt@2.1.16~install: Returned: code: 1  signal: null
21598 info lifecycle phantomjs-prebuilt@2.1.16~install: Failed to exec install script
21599 timing action:install Completed in 166ms
21600 verbose unlock done using /root/.npm/_locks/staging-13f878cc581c7945.lock for /root/oo/web-apps/build/node_modules/.staging
21601 timing stage:rollbackFailedOptional Completed in 32ms
21602 timing stage:runTopLevelLifecycles Completed in 51202ms
....
21604 verbose stack Error: phantomjs-prebuilt@2.1.16 install: `node install.js`
21604 verbose stack Exit status 1
21604 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
21604 verbose stack     at EventEmitter.emit (events.js:182:13)
21604 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
21604 verbose stack     at ChildProcess.emit (events.js:182:13)
21604 verbose stack     at maybeClose (internal/child_process.js:962:16)
21604 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
21605 verbose pkgid phantomjs-prebuilt@2.1.16
21606 verbose cwd /root/oo/web-apps/build
21607 verbose Linux 4.4.0-142-generic
21608 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
21609 verbose node v10.14.0
21610 verbose npm  v6.14.8
21611 error code ELIFECYCLE
21612 error errno 1
21613 error phantomjs-prebuilt@2.1.16 install: `node install.js`
21613 error Exit status 1
21614 error Failed at the phantomjs-prebuilt@2.1.16 install script.
21614 error This is probably not a problem with npm. There is likely additional logging output above.
21615 verbose exit [ 1, true ]
```

Please, give me ome direction?

**Comment by ShockwaveNN** [comment]
This is strange, could you `cd` to `web-apps/build` and `npm install` there
I just checked, there is warning about phantomjs deprecation, but no error

Or could you just use provided Dockerfile, it's simpler to use and I checked several days ago that it compile product correctly

**Comment by anasurimbo** [comment]
It appears the same output

```
root@oobuild:~/oo/web-apps/build# npm install
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

phantomjs-prebuilt@2.1.16 install /root/oo/web-apps/build/node_modules/phantomjs-prebuilt
node install.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/root/oo/web-apps/build/node_modules/phantomjs-prebuilt/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-26T06_59_22_279Z-debug.log

```

and tried

```
root@oobuild:~/oo/web-apps/build# npm install phantomjs-prebuilt@2.1.16
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated

> phantomjs-prebuilt@2.1.16 install /root/oo/web-apps/build/node_modules/phantomjs-prebuilt
> node install.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/root/oo/web-apps/build/node_modules/phantomjs-prebuilt/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-26T07_09_04_440Z-debug.log


```

and tryed 

```
root@oobuild:~/oo/web-apps/build# npm install phantomjs-prebuilt@2.1.16 --ignore-scripts
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm notice created a lockfile as package-lock.json. You should commit this file.
+ phantomjs-prebuilt@2.1.16
added 14 packages from 12 contributors in 36.629s

25 packages are looking for funding
  run `npm fund` for details

```

**Comment by ShockwaveNN** [comment]
Maybe try some of solutions?

https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle

Or last command fixed it for you?

**Comment by anasurimbo** [comment]
Last command appears to put stuff in right place.
If i start ./automate.py again. All changes to nmp_modules will be rewrited? Or the process just skip built npm modules?

**Comment by ShockwaveNN** [comment]
> If i start ./automate.py again. All changes to nmp_modules will be rewrited?

Not sure, probably not

Again, try to use Docker as described [here](https://github.com/ONLYOFFICE/build_tools#using-docker) if something goes wrong again

**Comment by anasurimbo** [comment]
Started automate.py. 
I will report results to you.
Thank you for help

**Comment by anasurimbo** [comment]
Process completed succesfully.

So the first error was a result of some hardware issue on AWS + ubuntu 14.04.06 ami
The second error was fixed  with --ignore-scripts flag.

Thanks fo help!
