### ISSUE TITLE
Compile error: "(...)/node_modules/sync-rpc/lib" && "Failed to make bytecode node10-x64"

### ISSUE THREAD

**Issue by npdserrano** [ONLYOFFICE/build_tools#414]
Hi,
I have a ubuntu-14.04.6-server-amd64, GCC 4.8.4,
I use the python command ./automate.py,
I have a breaking error when using build_tools:
```
> pkg@5.5.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v10.24.1-linux-x64          [====================] 100%

> Warning Cannot resolve ''./' + configCommon.get('services.CoAuthoring.server.editorDataStorage')'
  /home/user/server/build/server/DocService/sources/DocsCoServer.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve ''./' + config.get('storage.name')'
  /home/user/server/build/server/Common/sources/storage-base.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Failed to make bytecode node10-x64 for file /snapshot/server/build/server/Common/node_modules/openpgp/dist/openpgp.js
prebuild-install WARN install No prebuilt binaries found (target=v10.24.1 runtime=node arch=x64 libc= platform=linux)
prebuild-install WARN install No prebuilt binaries found (target=v10.24.1 runtime=node arch=x64 libc= platform=linux)
> pkg@5.5.1
> Warning Cannot resolve ''./' + config.get('storage.name')'
  /home/user/server/build/server/Common/sources/storage-base.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve ''./' + configCommon.get('services.CoAuthoring.server.editorDataStorage')'
  /home/user/server/build/server/DocService/sources/DocsCoServer.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Failed to make bytecode node10-x64 for file /snapshot/server/build/server/Common/node_modules/openpgp/dist/openpgp.js
prebuild-install WARN install No prebuilt binaries found (target=v10.24.1 runtime=node arch=x64 libc= platform=linux)
prebuild-install WARN install No prebuilt binaries found (target=v10.24.1 runtime=node arch=x64 libc= platform=linux)
> pkg@5.5.1
> Warning Cannot resolve 'name'
  /home/user/server/build/server/Metrics/node_modules/statsd/stats.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'name'
  /home/user/server/build/server/Metrics/node_modules/statsd/stats.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
prebuild-install WARN install No prebuilt binaries found (target=v10.24.1 runtime=node arch=x64 libc= platform=linux)
delete warning [folder not exist]: /home/user/build_tools/scripts/../../document-server-integration/web/documentserver-example/nodejs/node_modules
npm WARN OnlineEditorsExampleNodeJS@4.1.0 license should be a valid SPDX license expression

added 215 packages from 141 contributors and audited 215 packages in 3.008s

2 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 moderate, 1 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Traceback (most recent call last):
  File "./make.py", line 95, in <module>
    build_server.make()
  File "scripts/build_server.py", line 62, in make
    base.cmd_in_dir(sync_rpc_lib_dir, "patch", ["-N", "-i", patch_file])
  File "scripts/base.py", line 332, in cmd_in_dir
    os.chdir(dir)
OSError: [Errno 2] No such file or directory: '/home/user/build_tools/scripts/../../document-server-integration/web/documentserver-example/nodejs/node_modules/sync-rpc/lib'
Error (./make.py): 1
```

**Comment by ShockwaveNN** [comment]
> OSError: [Errno 2] No such file or directory: '/home/user/build_tools/scripts/../../document-server-integration/web/documentserver-example/nodejs/node_modules/sync-rpc/lib'

I think some repo failed to fetch during fetch phase, see any previous log for error related to `git clone`

**Comment by jpcyang** [comment]
I ran into the same compilation error, kept on thinking if I had done something wrong.

**Comment by ShockwaveNN** [comment]
Seems I was able to reporduce it, figuring out that happened

**Comment by ShockwaveNN** [comment]
Found out the reason
In `document-server-integration` subrepo we removed dependency of `sync-rpc` library which we patched

https://github.com/ONLYOFFICE/build_tools/commit/23d96dbd4dae438c75cac4fa252982e27b28c57e

This is on v7.0.0 branch and it should compile fine, I think you can apply this patch to master until we release v7.0.0

**Comment by ShockwaveNN** [comment]
DocumentServer v7.0.0 is released and this problem should be fixed
