### ISSUE TITLE
has-ansi not found

### ISSUE THREAD

**Issue by madscientist159** [ONLYOFFICE/build_tools#465]
On the `develop` branch using Debian Bullseye I run into an error with `has-ansi`:

```
up to date, audited 783 packages in 8s

55 packages are looking for funding
  run `npm fund` for details

31 vulnerabilities (2 low, 16 moderate, 12 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'has-ansi'
Require stack:
- /home/develop/onlyoffice/web-apps/build/node_modules/chalk/index.js
- /home/develop/onlyoffice/web-apps/build/node_modules/grunt-legacy-log-utils/index.js
- /home/develop/onlyoffice/web-apps/build/node_modules/grunt-legacy-log/index.js
- /home/develop/onlyoffice/web-apps/build/node_modules/grunt/lib/grunt.js
- /usr/local/lib/node_modules/grunt-cli/bin/grunt
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/develop/onlyoffice/web-apps/build/node_modules/chalk/index.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/develop/onlyoffice/web-apps/build/node_modules/chalk/index.js',
    '/home/develop/onlyoffice/web-apps/build/node_modules/grunt-legacy-log-utils/index.js',
    '/home/develop/onlyoffice/web-apps/build/node_modules/grunt-legacy-log/index.js',
    '/home/develop/onlyoffice/web-apps/build/node_modules/grunt/lib/grunt.js',
    '/usr/local/lib/node_modules/grunt-cli/bin/grunt'
  ]
}
Error (grunt): 1
```

This error is not present on `master`, where onlyoffice builds successfully.

**Comment by madscientist159** [comment]
Looks like installing `node-has-ansi` fixes the problem.
