### ISSUE TITLE
build framework7-react error

### ISSUE THREAD

**Issue by cnscottluo** [ONLYOFFICE/build_tools#669]
**Describe your problem**:

When executing build framework7-react, I get the following error:

```shell
Running "exec:webpack_app_build" (exec) task

> documenteditor@1.0.1 deploy-cell /mnt/f/onlyoffice/web-apps/vendor/framework7-react
> cross-env TARGET_EDITOR=cell NODE_ENV=production node ./build/build.js

>> /mnt/f/onlyoffice/web-apps/vendor/framework7-react/build/build.js:1
>> import webpack from 'webpack';
>>        ^^^^^^^
>>
>> SyntaxError: Unexpected identifier
>>     at Module._compile (internal/modules/cjs/loader.js:723:23)
>>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>>     at Module.load (internal/modules/cjs/loader.js:653:32)
>>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>>     at startup (internal/bootstrap/node.js:283:19)
>>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
>> npm
>> ERR! code ELIFECYCLE
>> npm
>> ERR! errno 1
>> npm
>> ERR! documenteditor@1.0.1 deploy-cell: `cross-env TARGET_EDITOR=cell NODE_ENV=production node ./build/build.js`
>> npm ERR! Exit status 1
>> npm ERR!
>> npm ERR! Failed at the documenteditor@1.0.1 deploy-cell script.
>> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>>
>> npm ERR! A complete log of this run can be found in:
>> npm ERR!     /root/.npm/_logs/2023-05-12T00_10_04_858Z-debug.log
>> Exited with code: 1.
>> Error executing child process: Error: Process exited with code 1.
```

**build_tools base repo version**:
master branch

**Operating system**:
Ubuntu 20.04

**Comment by cnscottluo** [comment]
i update node version from default 10.x to 14.x, it's work ok
