### ISSUE TITLE
[build fail] RPC failed transiently

### ISSUE THREAD

**Issue by Airscope** [ONLYOFFICE/build_tools#756]
Hello, ONLYOFFICE team, I am attempting to use this build_tools and I followed the guide to build the project on the Linux but I'm encountering a build error:

…
[fetch & build]: boost
[fetch & build]: cef
[fetch & build]: icu
[fetch & build]: openssl

[E2023-11-09T09:28:07.240775+08:00 1736 0 application.go:361] [P1781 09:07:33.609 client.go:312 W] RPC failed transiently (retry in 1s): rpc error: code = Internal desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 108.160.165.139:443: connect: connection refused {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"1s"}
[P1781 09:07:55.639 client.go:312 W] RPC failed transiently (retry in 2s): rpc error: code = Internal desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 108.160.165.139:443: connect: connection refused {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"2s"}
[P1781 09:08:18.697 client.go:312 W] RPC failed transiently (retry in 4s): rpc error: code = Internal desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 108.160.165.139:443: connect: connection refused {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"4s"}
[P1781 09:08:43.765 client.go:312 W] RPC failed transiently (retry in 8s): rpc error: code = Internal desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 108.160.165.139:443: connect: connection refused {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"8s"}
[P1781 09:09:12.809 client.go:312 W] RPC failed transiently (retry in 16s): rpc error: code = Internal desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 108.160.165.139:443: connect: connection refused {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"16s"}
[P1781 09:09:49.882 client.go:312 W] RPC failed transiently (retry in 32s): rpc error: code = Internal desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 108.160.165.139:443: connect: connection refused {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"32s"}
[P1781 09:10:42.928 client.go:312 W] RPC failed transiently (retry in 1m4s): rpc error: code = Internal desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 108.160.165.139:443: connect: connection refused {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"1m4s"}
[P1781 09:12:07.978 client.go:312 W] RPC failed transiently (retry in 2m8s): rpc error: code = Internal desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 108.160.165.139:443: connect: connection refused {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"2m8s"}
[P1781 09:14:37.021 client.go:312 W] RPC failed transiently (retry in 4m16s): rpc error: code = Internal desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 108.160.165.139:443: connect: connection refused {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"4m16s"}
[P1781 09:19:14.078 client.go:312 W] RPC failed transiently (retry in 8m32s): rpc error: code = Internal desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 108.160.165.139:443: connect: connection refused {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"8m32s"}
[P1781 09:28:07.236 client.go:357 W] RPC failed permanently: rpc error: code = Internal desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 69.171.247.32:443: connect: connection refused {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository"}Errors:
  failed to resolve infra/3pp/tools/virtualenv@version:2@16.7.12.chromium.7 (line 1): prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 69.171.247.32:443: connect: connection refused
[E2023-11-09T09:28:07.243476+08:00 1736 0 application.go:144] fatal error: failed to build venv: failed to build package : cipkg.Derivation{Name:"virtualenv", Platform:"", Builder:"builtin:cipdExport", Args:[]string{"infra/3pp/tools/virtualenv  version:2@16.7.12.chromium.7\n"}, Env:[]string(nil), Inputs:[]string(nil)}: failed to build derivation: failed to export packages: exit status 1
4.2
Traceback (most recent call last):
  File "/home/czy/code/oo-build/build_tools/scripts/base.py", line 193, in copy_dir
    shutil.copytree(get_path(src), get_path(dst))
  File "/usr/lib/python3.10/shutil.py", line 557, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: './v8/third_party'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/czy/code/oo-build/build_tools/./make.py", line 70, in <module>
    make_common.make()
  File "/home/czy/code/oo-build/build_tools/scripts/core_common/make_common.py", line 45, in make
    v8.make()
  File "/home/czy/code/oo-build/build_tools/scripts/core_common/modules/v8.py", line 78, in make
    v8_89.make()
  File "/home/czy/code/oo-build/build_tools/scripts/core_common/modules/v8_89.py", line 108, in make
    base.copy_dir("./v8/third_party", "./v8/third_party_new")
  File "/home/czy/code/oo-build/build_tools/scripts/base.py", line 197, in copy_dir
    print('Directory not copied. Error: %s' % e)
NameError: name 'e' is not defined. Did you mean: 're'?
Error (./make.py): 1
![image](https://github.com/ONLYOFFICE/build_tools/assets/16384912/1cb302cf-e66a-4d38-953d-1439ccc1c5ee)

I have tried to set http_proxy & https_proxy, but it did not work. Here is my environment information:
- Ubuntu 22.04.2 LTS
- Python 3.10.12
- git 2.42.0
- gcc 11.4.0

Looking forward to your response. :)

**Comment by igwyd** [comment]
Hi @Airscope, build_tools does not currently support Ubuntu 22.04, try using the version below. My last compile check was just 7 hours ago without errors on Ubuntu 20.04. I also see in your errors problems with getting dependencies. I guess this is because some countries block access to the addresses where we get dependencies. In this case, for assembly you can use the cloud servers in contries with more open internet access or VPN, etc.

**Comment by Airscope** [comment]
Thanks for your quick response and guidance. I'll switch to Ubuntu 20.04 and explore options for handling dependency access issues. Appreciate your help!

**Comment by haol666** [comment]
I use docker ubuntu:16.04 encountering this error too:
`P23818 03:20:23.842 client.go:312 W] RPC failed transiently (retry in 1s): rpc error: code = DeadlineExceeded desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 128.242.240.157:443: i/o timeout {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"1s"}
[P23818 03:20:54.872 client.go:312 W] RPC failed transiently (retry in 2s): rpc error: code = DeadlineExceeded desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 111.243.214.169:443: i/o timeout {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"2s"}
[P23818 03:21:26.903 client.go:312 W] RPC failed transiently (retry in 4s): rpc error: code = DeadlineExceeded desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 111.243.214.169:443: i/o timeout {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"4s"}
[P23818 03:22:00.910 client.go:312 W] RPC failed transiently (retry in 8s): rpc error: code = DeadlineExceeded desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 157.240.8.36:443: i/o timeout {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"8s"}
[P23818 03:22:38.946 client.go:312 W] RPC failed transiently (retry in 16s): rpc error: code = DeadlineExceeded desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 157.240.8.36:443: i/o timeout {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"16s"}
[P23818 03:23:24.987 client.go:312 W] RPC failed transiently (retry in 32s): rpc error: code = DeadlineExceeded desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 157.240.8.36:443: i/o timeout {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"32s"}
[P23818 03:24:27.047 client.go:312 W] RPC failed transiently (retry in 1m4s): rpc error: code = DeadlineExceeded desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 157.240.8.36:443: i/o timeout {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"1m4s"}
[P23818 03:26:01.112 client.go:312 W] RPC failed transiently (retry in 2m8s): rpc error: code = DeadlineExceeded desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 128.242.240.157:443: i/o timeout {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"2m8s"}
[P23818 03:28:39.241 client.go:312 W] RPC failed transiently (retry in 4m16s): rpc error: code = DeadlineExceeded desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 162.125.32.5:443: i/o timeout {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"4m16s"}
[P23818 03:33:25.346 client.go:312 W] RPC failed transiently (retry in 8m32s): rpc error: code = DeadlineExceeded desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 204.79.197.217:443: i/o timeout {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"8m32s"}`

**Comment by chenggwang** [comment]
> I use docker ubuntu:16.04 encountering this error too: `[P23818 03:33:25.346 client.go:312 W] RPC failed transiently (retry in 8m32s): rpc error: code = DeadlineExceeded desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 204.79.197.217:443: i/o timeout {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository", "sleepTime":"8m32s"} [P23818 03:42:27.442 client.go:357 W] RPC failed permanently: rpc error: code = DeadlineExceeded desc = prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 157.240.12.50:443: i/o timeout {"host":"chrome-infra-packages.appspot.com", "method":"ResolveVersion", "service":"cipd.Repository"} Error: prpc: sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion": dial tcp 157.240.12.50:443: i/o timeout. Bootstrap from scratch for linux-amd64 failed! Run the following commands to diagnose if this is repeating: export CIPD_HTTP_USER_AGENT_PREFIX=depot_tools/9f668bbff99167ba797888c6d322dd309f338aee/manual ./depot_tools/.cipd_client selfupdate -version-file ./depot_tools/cipd_client_version ./cipd: line 131: ./depot_tools/cipd_client_version.digests: No such file or directory Platform linux-amd64 is not supported by the CIPD client bootstrap: there's no pinned SHA256 hash for it in the *.digests file. ./depot_tools/bootstrap_python3: line 32: bootstrap-2@3.11.6.chromium.30_bin/python3/bin/python3: No such file or directory`

I got the same error, CIPD environment problem, I changed . /cipd script and it no longer reports that the file is not found, but there are there are a bunch of others.I think the main purpose of the compilation script is to serve the target project, and not to compile the tool to keep changing it as a project as well. This adds uncertainty. And there should be as few external dependencies as possible. Otherwise compilation tool environment problems bring dependency hell and it's too painful. It's not worth it to compile for the sake of compilation, our main purpose is OnlyOffice project, this will hinder the enthusiasm of the open source community contributors, which is the reason why the current project contributors are much smaller than CollaboraOnline.

**Comment by Mr-SunJun** [comment]
@Airscope Hi, has this problem been solved? I also have this problem!
![1728911109695](https://github.com/user-attachments/assets/3ee64f92-2e9f-4f9b-b7f5-fc0f360c03b6)
