### ISSUE TITLE
Error: Invalid protocol

### ISSUE THREAD

**Issue by lesens** [ONLYOFFICE/build_tools#782]
# Error: Invalid protocol:

*A download error occurred while previewing the document, and an error was found in the background: Invalid protocol:*

**Steps to reproduce the problem**:

*consult https://helpcenter.onlyoffice.com/installation/docs-community-compile.aspx After completing the compilation of this link, a preview test of the document was conducted, and there was a prompt indicating that the file could not be saved when loading the document.*

[2024-01-02T11:58:42.725] [ERROR] [localhost] [16567] [admin] nodeJS - error downloadFile:url=http://192.168.90.100/api/resource/16567;attempt=3;code:null;connect:null Error: Invalid protocol: 192.168.90.100:
    at Request.init (/snapshot/server/build/server/Common/node_modules/request/request.js:458:31)
    at new Request (/snapshot/server/build/server/Common/node_modules/request/request.js:127:8)
    at request (/snapshot/server/build/server/Common/node_modules/request/index.js:53:10)
    at Function.get (/snapshot/server/build/server/Common/node_modules/request/index.js:61:12)
    at /snapshot/server/build/server/Common/sources/utils.js
    at new Promise (<anonymous>)
    at downloadUrlPromiseWithoutRedirect (/snapshot/server/build/server/Common/sources/utils.js)
    at doRequest (/snapshot/server/build/server/Common/sources/utils.js)
    at Object.downloadUrlPromise (/snapshot/server/build/server/Common/sources/utils.js)
    at downloadFile (/snapshot/server/build/server/FileConverter/sources/converter.js)
    at downloadFile.next (<anonymous>)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)

**build_tools base repo version**:
7.5.1
**Operating system**:
Ubuntu 18.04
**Compiler version**:
7.5.1
In the error prompt, I found that it seems to have treated the IP address as a protocol，I have confirmed using wget on ubuntu that this uri can download the complete document, but I am unable to locate the cause of this issue

**Comment by igwyd** [comment]
Hello @lesens, sorry for the late reply. Did the compilation process complete successfully? Which the integration do you use? Try check with our test example https://api.onlyoffice.com/editors/example/nodejs.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
