### ISSUE TITLE
onlyoffice local build

### ISSUE THREAD

**Issue by kerry-weic** [ONLYOFFICE/build_tools#789]
# Describe your problem:

The following error occurs while building and running build_tools/Dockerfile:

````
Running "replace:insert-css" (replace) task
replace svg  connection_error.svg

Running "clean:files" (clean) task
>> 2 paths cleaned.

Done.
added 331 packages in 620.649s

> builder@1.0.1 build /data/server
> run-p install:*

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:173:14
    at FSReqCallback.wrapper [as oncomplete] (fs.js:563:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! builder@1.0.1 build: `run-p install:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the builder@1.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-02-20T02_45_28_366Z-debug.log
[git] update: desktop-sdk
[git] update: core
[git] update: document-server-integration
[git] update: sdkjs
[git] update: document-templates
[git] update: sdkjs-forms
[git] update: core-fonts
[git] update: server
[git] update: dictionaries
[git] update: onlyoffice.github.io
[git] update: web-apps
[git] update: desktop-apps
[fetch & build]: boost
delete warning [file not exist]: ./boost.data
[fetch & build]: cef
delete warning [file not exist]: ./cef_binary.7z.data
[fetch & build]: icu
[fetch & build]: openssl
delete warning [file not exist]: ./openssl.data
gn gen out.gn/linux_64 --args="v8_static_library=true is_component_build=false v8_monolithic=true v8_use_external_startup_data=false use_custom_libcxx=false treat_warnings_as_errors=false target_cpu=\"x64\" v8_target_cpu=\"x64\" is_debug=false is_clang=true use_sysroot=false"
[fetch & build]: hunspell
[fetch & build]: harfbuzz
[fetch]: hyphen
[fetch]: googletest
------------------------------------------
BUILD_PLATFORM: linux_64
------------------------------------------
make file: makefiles/build.makefile_linux_64
Error (npm): 1
---------------------------------------------
build branch: master
---------------------------------------------
---------------------------------------------
build modules: desktop builder server
---------------------------------------------
Error (./make.py): 1
````

2024-02-20T02_45_28_366Z-debug.log logs:
````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.18
3 info using node@v14.21.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle builder@1.0.1~prebuild: builder@1.0.1
6 info lifecycle builder@1.0.1~build: builder@1.0.1
7 verbose lifecycle builder@1.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle builder@1.0.1~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle builder@1.0.1~build: CWD: /data/server
10 silly lifecycle builder@1.0.1~build: Args: [ '-c', 'run-p install:*' ]
11 silly lifecycle builder@1.0.1~build: Returned: code: 1  signal: null
12 info lifecycle builder@1.0.1~build: Failed to exec build script
13 verbose stack Error: builder@1.0.1 build: `run-p install:*`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid builder@1.0.1
15 verbose cwd /data/server
16 verbose Linux 3.10.0-1160.88.1.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v14.21.3
19 verbose npm  v6.14.18
20 error code ELIFECYCLE
21 error errno 1
22 error builder@1.0.1 build: `run-p install:*`
22 error Exit status 1
23 error Failed at the builder@1.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
````

**build_tools base repo version**:
master
**Operating system**:
Ubuntu 16.04
**Compiler version**:

**Comment by igwyd** [comment]
Hello @kerry-weic, i checked compilation with our [Dockerfile](https://github.com/ONLYOFFICE/build_tools/blob/master/Dockerfile), no errors for me. Please try it again on clean updated server. I recommend doing this on the server with not less then 4 cpu 8 RAM and outside Great firewall of china.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
